apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app.kubernetes.io/name: hello
  ports:
    - name: hello-port
      protocol: TCP
      port: 5678 # Default port for image hashicorp/http-echo
