apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app.kubernetes.io/name: hello
spec:
  containers:
    - name: hello
      image: kennship/http-echo # Source: https://github.com/kennship/http-echo
