version: "3.9"

services:
  registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - 5000:5000
    volumes:
      - ./data:/var/lib/registry
      - ./config.simple.yml:/etc/docker/registry/config.yml
    restart: on-failure

  ui:
    image: joxit/docker-registry-ui:latest
    container_name: docker-registry-ui
    environment:
      - REGISTRY_TITLE=Local Docker Registry
      - REGISTRY_URL=http://localhost:5000
      - SINGLE_REGISTRY=true
    ports:
      - 5001:80
    depends_on:
      - registry
    restart: on-failure

networks:
  default:
    name: docker-registry_network
